// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package list_rooms
//

// Package list_rooms is a generated GoMock package.
package list_rooms

import (
	context "context"
	reflect "reflect"

	rooms "github.com/tcarzverey/bookings/internal/repository/rooms"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomsRepository is a mock of RoomsRepository interface.
type MockRoomsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomsRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomsRepositoryMockRecorder is the mock recorder for MockRoomsRepository.
type MockRoomsRepositoryMockRecorder struct {
	mock *MockRoomsRepository
}

// NewMockRoomsRepository creates a new mock instance.
func NewMockRoomsRepository(ctrl *gomock.Controller) *MockRoomsRepository {
	mock := &MockRoomsRepository{ctrl: ctrl}
	mock.recorder = &MockRoomsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomsRepository) EXPECT() *MockRoomsRepositoryMockRecorder {
	return m.recorder
}

// ListRooms mocks base method.
func (m *MockRoomsRepository) ListRooms(ctx context.Context) ([]rooms.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].([]rooms.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRoomsRepositoryMockRecorder) ListRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRoomsRepository)(nil).ListRooms), ctx)
}
