// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package list_rooms

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tcarzverey/bookings/internal/repository/rooms"
)

// NewMockRoomsRepositoryMockery creates a new instance of MockRoomsRepositoryMockery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomsRepositoryMockery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomsRepositoryMockery {
	mock := &MockRoomsRepositoryMockery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomsRepositoryMockery is an autogenerated mock type for the RoomsRepository type
type MockRoomsRepositoryMockery struct {
	mock.Mock
}

type MockRoomsRepositoryMockery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomsRepositoryMockery) EXPECT() *MockRoomsRepositoryMockery_Expecter {
	return &MockRoomsRepositoryMockery_Expecter{mock: &_m.Mock}
}

// ListRooms provides a mock function for the type MockRoomsRepositoryMockery
func (_mock *MockRoomsRepositoryMockery) ListRooms(ctx context.Context) ([]rooms.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRooms")
	}

	var r0 []rooms.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]rooms.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []rooms.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rooms.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomsRepositoryMockery_ListRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRooms'
type MockRoomsRepositoryMockery_ListRooms_Call struct {
	*mock.Call
}

// ListRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomsRepositoryMockery_Expecter) ListRooms(ctx interface{}) *MockRoomsRepositoryMockery_ListRooms_Call {
	return &MockRoomsRepositoryMockery_ListRooms_Call{Call: _e.mock.On("ListRooms", ctx)}
}

func (_c *MockRoomsRepositoryMockery_ListRooms_Call) Run(run func(ctx context.Context)) *MockRoomsRepositoryMockery_ListRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomsRepositoryMockery_ListRooms_Call) Return(rooms1 []rooms.Room, err error) *MockRoomsRepositoryMockery_ListRooms_Call {
	_c.Call.Return(rooms1, err)
	return _c
}

func (_c *MockRoomsRepositoryMockery_ListRooms_Call) RunAndReturn(run func(ctx context.Context) ([]rooms.Room, error)) *MockRoomsRepositoryMockery_ListRooms_Call {
	_c.Call.Return(run)
	return _c
}
