// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bookings

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID        int32
	RoomID    int32
	UserID    string
	Capacity  int32
	Status    int32
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Room struct {
	ID        int32
	Name      string
	Capacity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
