// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bookings

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
update bookings
set
    status = 'cancelled',
    updated_at = now()
where id = $1
returning
    id,
    room_id,
    user_id,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
`

type CancelBookingRow struct {
	ID        int32
	RoomID    int32
	UserID    string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Status    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CancelBooking(ctx context.Context, id int32) (CancelBookingRow, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i CancelBookingRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
insert into bookings (room_id, user_id, start_time, end_time)
values ($1, $2, $3, $4)
returning
    id,
    room_id,
    user_id,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
`

type CreateBookingParams struct {
	RoomID    int32
	UserID    string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

type CreateBookingRow struct {
	ID        int32
	RoomID    int32
	UserID    string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Status    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.RoomID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
select
    id,
    room_id,
    user_id,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
from bookings
where id = $1
`

type GetBookingRow struct {
	ID        int32
	RoomID    int32
	UserID    string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Status    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetBooking(ctx context.Context, id int32) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
select
    id,
    room_id,
    user_id,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
from bookings
order by id
`

type ListBookingsRow struct {
	ID        int32
	RoomID    int32
	UserID    string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Status    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListBookings(ctx context.Context) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByPeriod = `-- name: ListBookingsByPeriod :many
select
    id,
    room_id,
    user_id,
    start_time,
    end_time,
    status,
    created_at,
    updated_at
from bookings
where
    start_time < $1
  and end_time > $2
order by room_id, start_time
`

type ListBookingsByPeriodParams struct {
	Start  pgtype.Timestamptz
	Finish pgtype.Timestamptz
}

type ListBookingsByPeriodRow struct {
	ID        int32
	RoomID    int32
	UserID    string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Status    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListBookingsByPeriod(ctx context.Context, arg ListBookingsByPeriodParams) ([]ListBookingsByPeriodRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByPeriod, arg.Start, arg.Finish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByPeriodRow
	for rows.Next() {
		var i ListBookingsByPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
