openapi: 3.0.0
info:
  title: Responses
  version: 1.0.0
paths: {}

components:
  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './error.yaml#/components/schemas/Error'
    401:
      description: Unauthenticated
      content:
        application/json:
          schema:
            $ref: './error.yaml#/components/schemas/Error'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: './error.yaml#/components/schemas/Error'
    429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: './error.yaml#/components/schemas/Error'
    500:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: './error.yaml#/components/schemas/Error'