// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tcarzverey/bookings/internal/models"
)

// NewMockListRoomsUsecaseMockery creates a new instance of MockListRoomsUsecaseMockery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListRoomsUsecaseMockery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListRoomsUsecaseMockery {
	mock := &MockListRoomsUsecaseMockery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListRoomsUsecaseMockery is an autogenerated mock type for the ListRoomsUsecase type
type MockListRoomsUsecaseMockery struct {
	mock.Mock
}

type MockListRoomsUsecaseMockery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListRoomsUsecaseMockery) EXPECT() *MockListRoomsUsecaseMockery_Expecter {
	return &MockListRoomsUsecaseMockery_Expecter{mock: &_m.Mock}
}

// ListRooms provides a mock function for the type MockListRoomsUsecaseMockery
func (_mock *MockListRoomsUsecaseMockery) ListRooms(ctx context.Context) ([]models.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRooms")
	}

	var r0 []models.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListRoomsUsecaseMockery_ListRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRooms'
type MockListRoomsUsecaseMockery_ListRooms_Call struct {
	*mock.Call
}

// ListRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListRoomsUsecaseMockery_Expecter) ListRooms(ctx interface{}) *MockListRoomsUsecaseMockery_ListRooms_Call {
	return &MockListRoomsUsecaseMockery_ListRooms_Call{Call: _e.mock.On("ListRooms", ctx)}
}

func (_c *MockListRoomsUsecaseMockery_ListRooms_Call) Run(run func(ctx context.Context)) *MockListRoomsUsecaseMockery_ListRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListRoomsUsecaseMockery_ListRooms_Call) Return(rooms []models.Room, err error) *MockListRoomsUsecaseMockery_ListRooms_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockListRoomsUsecaseMockery_ListRooms_Call) RunAndReturn(run func(ctx context.Context) ([]models.Room, error)) *MockListRoomsUsecaseMockery_ListRooms_Call {
	_c.Call.Return(run)
	return _c
}
